SELECT 	o.Account_Subscription_Year__c as "Account Subscription Year"
		,o.AccountId as "Opportunity Account Id"
		,o.Amount__USD as "Opportunity Amount USD"
		,o.Closed_Lost_Date__c as "Opportunity Closed Lost Date"
		,o.Closed_Won_Date__c as "Opportunity Closed Won Date"
		,o.CloseDate as "Opportunity Close Date"
        ,o.CreatedDate as "Opportunity Create Date"
		,o.Details_of_Lost_Opportunity__c as "Details of Lost Opportunity"
		,o.Id_ as "Opportunity Id"
		,o.IsWon as "Is Won?"
		,o.Liferay_Version__c as "Liferay Version"
		,o.Name as "Opportunity Name"
		,o.Opportunity_Age_to_Close__c as "Opportunity Age to Close"
		,o.AccountAddress_Shipping_Address_Region__c as "Account Address Shipping Address Region"
		,o.AccountAddress_Billing_Address_Region__c as "Account Address Billing Address Region"
		,o.Product_Name__c as "Product Name"
		,o.Renewal_Dates__c as "Renewal Dates"
		,o.Sold_By__c as "Sold By"
		,o.StageName as "Stage Name"
		,o.Term_Length__c as "Term Length"
		,o.Term_Type__c as "Term Type"
		,o.Type_ as "Opportunity Type"
		,CONCAT("https:#na5.salesforce.com/" ,o.Id_) as "Opportunity URL"
		,a.Account_Subscription_End_Date__c as "Account Subscription End Date"
		,a.Account_Subscription_Start_Date__c as "Account Subscription Start Date"
		,a.Active_Subscription__c as "Active Subscription?"
		,a.BillingCountry as "Billing Country"
		,a.Id_ as "Account Id"
		,a.Industry as "Account Industry"
		,a.Name as "Account Name"
		,a.OwnerId as "Account Owner Id"
		,a.Active_Service_Partner__c as "Account Active Service Partner"
		,a.Partnership_End_Date__c as "Account Partnership End Date"
		,a.Partnership_Start_Date__c as "Account Partnership Start Date"
		,a.RecordTypeId as "Account Record Type Id"
		,a.Type_ as "Account Type"
		,a.Lifetime_Value_for_Account__c as "Lifetime Value for Account"
FROM Account_ as a
LEFT JOIN Opportunity as o 
on a.Id_ = o.AccountId
